
/* =========================================================================

     Alexandre da Silva Simoes and Esther Luna Colombini
     <assimoes@sorocaba.unesp.br> <esther@ita.br>
     http://www.sorocaba.unesp.br/professor/assimoes
     This code is part of ProSE - Problem Search Environment
     Software under GNU General Public License V.3
     Last update: September, 2012.

   ========================================================================= */
   

#define BTN_STEP         101
#define BTN_RUN          102
#define BTN_EXIT         103
#define BTN_INFO_LIST    104
#define BTN_INFO_VISIT   105
#define COMBO_ALG        200
#define CHK_VISITED      300
#define CHK_VISUAL       301

#define ERROR_RULES               1  //Too many rules. Increase MAX_RULES in <Search.h>
#define ERROR_MEMORY              2  //Can't allocate memory.
#define ERROR_QUEUE_REMOVE        3  //Attempt to remove a node from an empty queue.
#define ERROR_STACK_REMOVE        4  //Attempt to remove a node from an empty stack.
#define ERROR_NULL_POINTER        5  //There is a pointer the a null node.
#define ERROR_USER_INITIALIZATION 6  //There is an error on user problem initialization
#define ERROR_NULL_NODE           7  //NULL node generated by expandNode (error in a rule in ProblemRules)

#define SM_BREAKPOINT 1
#define SM_CONTINOUS 2

void printListBox(char *);
void printVisitedBox(char *);
void printSucessorsBox(char *);
void printOrderBox(char *);
void printNodeBox(char *);
void printNodeValueBox(char *);
void printFatherBox(char *);
void printRouteBox(char *);
void printDepthBox(char *);
void printGoalBox(char *);
void printStartValueBox(char*);
void printNodeValueBox(char*);
void printEndMessage(void);
int printGoalMessage(void);
int useVisit(void);
int useDisplay(void);
void printErrorMessage(int);
void printEndMessage(void);
extern int state_machine;
extern int search_mode;
extern int visual_mode;
